#keytool -genkeypair -keystore myKeystore2.p12 -storetype PKCS12 -storepass 123456 -alias ks-localhost -keyalg RSA -keysize 2048 -validity 99999 -dname "CN=My SSL Certificate, OU=My Team, O=My Company, L=My City, ST=My State, C=SA" -ext san=dns:localhost,ip:127.0.0.1
server:
  port: 443
  tomcat:
    accesslog:
      enabled: true
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:4070046_www.skrtu.com.pfx
    key-store-password: brlc286g